# Unused plots

```{r}
# Load necessary libraries
library(tidyverse)
library(ggthemes)

df <- read_csv("../data/proc/dwa_full.csv")
df_simple <- read_csv("../data/proc/dwa_simple.csv")
```


## Gini / Theil in Europe

```{r}
df_gini <- read_csv("../data/proc/gini_simple.csv")
```

```{r}
df_gini %>%
  filter(
    ASSET %in% c("HW_NET"), #housing asset
    REF_AREA %in% c("DE", "IT","NL", "AT", "ES", "FR", "BE", "PT") # selected countries
    ) %>%
  ggplot(aes(x = TIME_PERIOD)) +
    geom_line(aes(y = GINI, color = REF_AREA)) 
```

## P10 P50 ratios

```{r}
df_filter %>%
  filter(
    REF_AREA %in% c("DE", "BE", "IT", "AT", "ES", "FR"),
    DWA_GRP %in% c("B50", "D10"),
    UNIT_MEASURE == "EUR_R_POP"
  ) %>%
  select(TIME_PERIOD, REF_AREA, DWA_GRP, TW_NET) %>%
  group_by(TIME_PERIOD, REF_AREA) %>%
  summarise(
    ratio = TW_NET[DWA_GRP == "D10"] / TW_NET[DWA_GRP == "B50"]
  ) %>%
  ggplot(aes(x = TIME_PERIOD, y = ratio, color=REF_AREA)) +
    geom_line()
```
## Covariance per Decile across Europe

```{r}
df_simple %>%
  filter(
    TIME_PERIOD == "2023-01-01",
    UNIT_MEASURE == "EUR_R_POP",
    DWA_GRP %in% c("B50", "D06", "D07", "D08", "D09", "D10"),
  ) %>%
  select(REF_AREA, DWA_GRP, TW_NET) %>%
  # variance in between the countries
  group_by(DWA_GRP) %>%
  summarise(
    minimum = min(TW_NET, na.rm = TRUE),
    maximum = max(TW_NET, na.rm = TRUE),
    mean = mean(TW_NET, na.rm = TRUE),
    median = median(TW_NET, na.rm = TRUE),
    sd = sd(TW_NET, na.rm = TRUE),
    cov = sd / mean * 100 # coefficient of variation
  )
```
= not much different!

## Largest Asset Europe

```{r}
df %>%
  filter(
    TIME_PERIOD == "2023-01-01",
    UNIT_MEASURE == "EUR",
    DWA_GRP == "_Z",
    REF_AREA == "EU",
    INSTR_ASSET %in% c("F51M", "NUB", "F62", "F52", "F511", "F3", "NUN", "F2M")
  ) %>%
  select(INSTR_ASSET, OBS_VALUE) %>%
  arrange(desc(OBS_VALUE)) %>%
  mutate(
    asset_share = OBS_VALUE / sum(OBS_VALUE) * 100, # calculate share of total assets
  )
```
