## Related Literature {#sec-literature}

Housing occupies a central place in the literature on both the macroeconomy and the distribution of wealth.

In the wake of the financial crisis of 2008, research has focused on the role of asset price bubbles, particularly real estate, in the business cycle. @jordaLeveragedBubbles2015 analyze the last 140 years to show that bubbles associated with a credit boom pose the greatest risk for macroeconomic stability. Subsequent recessions are deeper and longer than ones with low credit growth. In a related paper, @jordaGreatMortgagingHousing2016 focus on the role of real estate finance. Using a newly constructed dataset, they document that the share of mortgages in total debt has risen, from 30% in 1900 to 60% today. Furthermore, they emphasise the associated risks with mortgage lending booms. They are increasingly linked to recessions and have deep repercussions for the business cycle.

Other contributions take a long-run view on housing as an asset class. @knollNoPriceHome2017 document the evolution of housing prices since 1870 to find a "hockey stick pattern" [@knollNoPriceHome2017, p. 332] of fast rising prices after World War II. They show that it is to 80% made up by the underlying value of land, with substantial heterogeneity across countries. @jordaRateReturnEverything2019 analyse the same time frame and document that total returns on housing are historically similar to equity returns, even though the latter is associated with more risk. Additionally, they show that almost half of all capital stock in developed economies is made up of housing [@jordaRateReturnEverything2019, p. 8].

Beyond its macroeconomic role, housing is also a core driver of wealth inequality. The surge of research on long-run inequality, most prominently initiated by @pikettyCapitalBackWealthIncome2014a, has emphasized the post-war rise of wealth inequality and wealth-to-income ratios in advanced economies. A large part of this increase is attributed to housing assets, which play a decisive role in shaping modern wealth dynamics[^l1].

The renewed interest in inequality and its measurement inspired the development of distributional national accounts. These new datasets aim to link national accounts with survey data to generate macroeconomically consistent estimates of the wealth / income distribution. First presented for the US income distribution by @pikettyDistributionalNationalAccounts2018 and wealth distribution by @battyDistributionalFinancialAccounts2022, they are now available as well for european income [@blanchetHowUnequalEurope2019] and wealth distributions [@blatnikIntroducingDistributionalWealth2024]. The latter is the main dataset used in this thesis, further explored in @sec-data.

Wealth accumulation is shaped by three main drivers: labor income, savings rates, and capital gains [@saezWealthInequalityUnited2016, p.28]. The first two combine into the savings effect, while the latter reflects the valuation effect. Inequality in any of these channels across different parts of the population translates into increased wealth inequality. For instance, higher income inequality, ceteris paribus, leads to higher wealth inequality because households at the top receive a larger flow of income, which, even under identical savings rates, allows them to accumulate wealth at a faster pace. Likewise, differential capital gains from rising asset prices can increase wealth inequality even when income and savings rates remain unchanged. 

@blanchetWealthInequalityDynamics2023 research these drivers empirically, comparing the dynamics of wealth inequality in the US and Europe. The authors employ decomposition techniques to show that the higher income inequality as well as the decline in house prices after the financial crisis are responsible for the stronger increase in US wealth inequality compared to Europe. In the latter, valuation effects were more important, while in the former savings effects played a larger role in explaining inequality. This highlights that the relative role of savings and valuation channels differs across regions, and that capital gains deserve closer attention in inequality research.

A growing line of literature therefore focuses explicitly on asset prices as a central driver of wealth inequality. @kuhnIncomeWealthInequality2020 use the newly constructed Historical Survey of Consumer Finances ranging back to 1948 to document the reactions of the top 10% of the US wealth distribution to stock and house prices [@kuhnIncomeWealthInequality2020, p.37]. They find that the share of the top decile of the wealth distribution reacts negatively to increases in house prices and the opposite with respect to stock prices, mostly due to differential exposure in Household portfolios [@kuhnIncomeWealthInequality2020, p.34]. Additionally, they find that the valuation channel is predominantly responsible for shifts in the wealth distribution, especially in the lower half of the population [@kuhnIncomeWealthInequality2020, p.42]. 

A similar avenue is followed by @adamDistributionalConsequencesAsset2016. They use data from the 2013 wave of the Household Finance and Consumption Survey (HFCS) to simulate the effect of asset gains on European household portfolios by scaling portfolio positions by a 10% increase in value. The authors document an increase in wealth inequality in response to rising stock prices and a decrease in response to house price apprecations, similar to @kuhnIncomeWealthInequality2020. They highlight a large heterogeneity in real estate gains across Europe, particularly in the lower parts of the distribution. Additionally, they document the existence of a group of households that do not gain noticable amounts from asset prices, making up ca. 20% of the Eurozone population.

@martinez-toledanoHousePriceCycles2020 focuses specifically on the effects of house price cycles on wealth inequality in Spain. She puts a special emphasis on the role of portfolio reshuffling in different phases of a house price cycle. In booms, the share of the top decile decreases to the benefit of the bottom 50% and especially the middle 40%, while in busts that effect reverses. The top wealth holders are faster in adjusting their portfolio towards other assets in downturns, while the rest of the population faces portfolio adjustment frictions in the form of moving costs and mortgage commitments.

While these studies establish asset prices as a key driver of wealth inequality, they are limited by either long-run survey data or a single-country focus. This thesis takes a different approach by using the ECB’s official Distributional Wealth Accounts, which provide macro-consistent quarterly data for countries in the euro area. This allows for a closer empirical look at short-term valuation effects in recent years and a systematic comparison of heterogeneity across national contexts.

Since exposure to asset prices depends on portfolios, theory and empirical evidence on portfolio choice are crucial. @coccoPortfolioChoicePresence2005 presents a theoretical model of optimal portfolio allocation to explain the different choices along the age and income distribution. The author highlights the cost of participating in the equity market, which presents a barrier for poorer and younter households, especially after investment in housing. Additionally, risks associated with house price cycles reduces risk appetite, and in turn exposure to stock markets. This effect is especially pronounced for lower parts of the wealth distribution. 

@sierminskaOwnNotOwn2013 document these portfolio differences for age cohorts empirically across Europe and North America, highlighting the role of institutions in portfolio choices. A description of household balance sheets across socio-economic groups is provided by @causaHousingWealthAccumulation2019 for OECD Countries. They highlight housing as the most important asset, especially for the middle class, but document pronounced variations in countries at the bottom of the wealth distribution  [@causaHousingWealthAccumulation2019, p.22]. Additionally, they stress the importance of mortages, due to the increased vulnerability in housing price busts or elevated interest rate periods for leveraged households [@causaHousingWealthAccumulation2019, p.30].

Another explanation for differential gains from assets along the distribution are heterogeneous rates of return on assets. Richer households have higher profits than poorer households even when controlling for portfolio differences. This relationship is documented by @fagerengHeterogeneityPersistenceReturns2020 using detailed norwegian individual tax records, who find that this effect is persistent across generations. Similar heterogenous patterns are found by @bachRichPickingsRisk2020 in swedish tax data. @wolffHeterogenousRatesReturn2025 looks specifically at rates of returns on real estate in the US, and finds that rich households earn significantly more on their investments. Counter-intuitively, the author finds that increasing rates of return on housing still decreases wealth inequality, due to the larger share of the asset in portfolios of poorer households.

The thesis relates closely to the literature examining the cross-country wealth differences in the European Union. The central role of housing is highlighted by @biewenShapeWealthDistribution2025, who find that homeownership is the main household characteristic that explains these differences. Similarly, @kaasWealthInequalityHomeownership2019 emphasize that homeownership is the channel to explain the differences, with home ownership rates strongly negatively related to wealth inequality in the 9 largest european countries. A large part of these differences can be accounted for by distinct home ownership rates in the bottom half of the wealth distribution. Furthermore, they decompose inequality into inequality between owners and renters and intra-group inequalities and find that the the former is primarily responsible for the relationship between inequality and homeownership. @mathaHouseholdWealthEuro2017 adds to this the role of diverse housing price dynamics to explain the variations in net wealth accumulated across Europe. Both factors together can explan more than 50% of the wealth differences in Europe.

A methodology similar to the one in this thesis was first used by @wolffTopHeavyStudy1995 [p.77] for US wealth inequality between 1922 and 1989. The author regressed the wealth share of the top 1% on the share of income accrued by the group and the ratio of stock prices to housing prices. Both factors are statistically significant, with the prices ratio explaining most of the divergence of wealth and income inequality between 1945 and 1979. Most recently, @kuhnIncomeWealthInequality2020 use a similar regression to describe the "race between the stock market and the housing market" [@kuhnIncomeWealthInequality2020, p. 37]. They regress the first differences of the wealth share hold by the top 10% of the US american wealth distribution on the first differences in housing prices, stock prices (proxied by the S&P 500) and the share of income going to the top 10%. The results indicate a negative reaction of the wealth share to house prices and a positive one to stock prices, although with limited statistical significance due to small sample size. @fullerHousingPricesWealth2020 use similar explanatory variables in a panel regression of OECD countries to explain the rising wealth-to-income ratios by @pikettyCapitalBackWealthIncome2014a. The authors find that the increase is mostly explained by rising house prices as well as to a lesser extent prices of other assets.

This thesis contributes by examining how different segments of the wealth distribution respond to changes in stock and housing prices. In addition to estimates for the euro area as a whole, it provides country-level evidence that highlights the heterogeneity of these effects. The next section introduces the dataset underpinning this analysis and outlines its key features.

[^l1]: The measurement of capital by Piketty was criticised by @bonnetDoesHousingCapital2014, who find that using (imputed) rent as housing valuation, Piketty's fast rising capital-income ratios are actually stable. @allegreDoesHousingWealth2015 outline internal incosistencies in their subsequent response while emphasizing the central contribution of housing in explaining the wealth dynamics. A summary of the role of housing in the debate around Piketty's work is provided by @stephensPikettyInequalityHousing2017.

